version: '3.7'

services:
  currency-exchange-service:
    image: ak088135/mmv2-currency-exchange-service:0.0.1-SNAPSHOT
    ports:
    - 8000:8000
    networks:
    - currency-network
    depends_on:
    - eureka-naming-server
    - rabbitmq
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka-naming-server:8761/eureka/
    - spring.zipkin.baseUrl=http://zipkin-server:9411/
    - RABBIT_URI= amqp://guest:guest@rabbitmq:5672
    - spring_rabbitmq_host=rabbitmq
    - spring_zipkin_sender_type=rabbit
    
    links:
    - eureka-naming-server
  
  
  
  currency-conversion-service:
    image: ak088135/mmv2-currency-conversion-service:0.0.1-SNAPSHOT
    ports:
    - 8100:8100
    networks:
    - currency-network
    depends_on:
    - eureka-naming-server
    - rabbitmq
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka-naming-server:8761/eureka/
    - spring.zipkin.baseUrl=http://zipkin-server:9411/
    - RABBIT_URI= amqp://guest:guest@rabbitmq:5672
    - spring_rabbitmq_host=rabbitmq
    - spring_zipkin_sender_type=rabbit
    links:
    - eureka-naming-server
  
  
  
  api-gateway-service:
    image: ak088135/mmv2-api-gateway-service:0.0.1-SNAPSHOT
    ports:
    - 8765:8765
    networks:
    - currency-network
    depends_on:
    - eureka-naming-server
    - rabbitmq
    environment:
    - eureka.client.serviceUrl.defaultZone=http://eureka-naming-server:8761/eureka/
    - spring.zipkin.baseUrl=http://zipkin-server:9411/
    - RABBIT_URI= amqp://guest:guest@rabbitmq:5672
    - spring_rabbitmq_host=rabbitmq
    - spring_zipkin_sender_type=rabbit
    links:
    - eureka-naming-server
  
  
  
  eureka-naming-server:
    image: ak088135/mmv2-eureka-naming-server:0.0.1-SNAPSHOT
    ports:
    - 8761:8761
    networks:
    - currency-network
  
  
  
  zipkin-server:
    image: openzipkin/zipkin:2.23
    ports:
    - 9411:9411
    networks:
    - currency-network
    environment:
      RABBIT_URI: amqp://guest:guest@rabbitmq:5672
    depends_on:
    - rabbitmq
    restart: always
  
  
  
  rabbitmq:
    image: rabbitmq:3.5.3-management
    ports:
    - 5672:5672
    - 15672:15672
    networks:
    - currency-network

networks:
  currency-network: