spring:
  application:
    name: eureka-naming-server
  config:
    import:
    - optional:configserver:http://localhost:8888

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

server:
  port: 8761