spring:
  config:
    import:
    - optional:configserver:http://localhost:8888
  application:
    name: limits-service
  profiles:
    active:
    - dev
  cloud:
    config:
      profile: qa # cloud config give more priority than active profile
 
limits-service:
  minimum: 5
  maximum: 995