spring:
  application:
    name: currency-conversion-service
  config:
    import:
    - optional:configserver:http://localhost:8888
  sleuth:
    sampler:
      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411/
#    sender:
#      type: rabbit

server:
  port: 8100
  
eureka:
  client:
    service-url:
      default-zone:  http://localhost:8761/eureka
      
#  instance:
#    hostname: localhost
