spring:
  application:    name: currency-exchange-service  config:    import:    - optional:configserver:http://localhost:8888
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true #table to be created first so that insertion will happen
  datasource:    url: jdbc:h2:mem:testdb 
    driver-class-name: org.h2.Driver
    username: test
    password: test
  h2:    console:      enabled: true
  sleuth:    sampler:      probability: 1.0
eureka:
  client:
    service-url:
      default-zone:  http://localhost:8761/eureka
#  instance:#    hostname: localhost  

resilience4j:  retry:    instances:      sample-api:
        max-attempts: 5
        wait-duration: 1s
        enable-exponential-backoff: true
  circuitbreaker:    instances:
      sample-api-2:
        minimumNumberOfCalls: 20
        failure-rate-threshold: 90
  ratelimiter:    instances:      sample-api-3:
        limit-for-period: 2
        limit-refresh-period: 10s
  bulkhead:    instances:      sample-api-4:
        max-concurrent-calls: 10  
                    

server:
  port: 8000