spring:
  application:
    name: api-gateway-service
  config:    import:    - optional:configserver:http://localhost:8888
#for accessing url from api gateway
#  cloud:
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
 
  sleuth:    sampler:      probability: 1.0
#  zipkin:
#    base-url: http://localhost:9411/
#    sender:
#      type: rabbit
      
eureka:
  client:
    service-url:
      default-zone:  http://localhost:8761/eureka

server:  port: 8765         